arm:
  # Publish all joint states -----------------------------------
  #velocity_controller:
  #  type: joint_state_controller/JointStateController
  #  publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint1
    pid: {p: 10000, i: 3000, d: 5000}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint2
    pid: {p: 10000, i: 3000, d: 5000}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint3
    pid: {p: .0300, i: .30, d: .53}
